CREATE TABLE users
(
    id                int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login         varchar(64) NOT NULL UNIQUE,
    password          varchar(64) NOT NULL,
    registration_time TIMESTAMP
);

CREATE TABLE vehicle
(
    vehicle_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacture varchar(64)    NOT NULL,
    engineType  varchar(64)    NOT NULL,
    model       varchar(64)    NOT NULL,
    price       decimal NOT NULL,
    age         int,
    weight      int
);